In [1]:
import numpy as np
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [3]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.full((3,3),1.0)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
a1 = np.array([4,5,6,4,5])
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [6]:
print(a1)
np.ones_like(a1)

[4 5 6 4 5]


array([1, 1, 1, 1, 1])

In [7]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [10]:
np.random.random((3,3))

array([[0.38338166, 0.18194185, 0.79565041],
       [0.32126624, 0.43122265, 0.47643429],
       [0.78514858, 0.73505928, 0.5686679 ]])

In [12]:
np.random.randint(0,10,(3,3))

array([[9, 3, 8],
       [6, 8, 9],
       [6, 3, 8]])

In [13]:
np.random.normal(0,1,size = (3,3))

array([[-0.68768008, -1.53991662,  0.33109109],
       [-1.52354571,  0.25434385,  0.76546062],
       [ 1.50140051,  1.65434987,  1.46162067]])

In [14]:
np.random.rand(3,3)

array([[0.39948334, 0.18403235, 0.13995678],
       [0.68047073, 0.41170221, 0.02531922],
       [0.49954064, 0.12779423, 0.04527633]])

In [15]:
np.random.randn(3,3)

array([[ 1.59433743, -0.02868717,  1.04027071],
       [ 0.36259524, -1.32209571,  0.96935732],
       [-0.80167304,  0.72108438, -0.07870752]])

In [16]:
np.zeros(20,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,3),dtype = bool) 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
np.full((3,3),1.0,dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
date = np.array('2020-01-01',dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [20]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [21]:
datetime = np.datetime64('2020-06-01 12:00:12.34','ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [22]:
def array_info(array):
    print(array)
    print('ndim:',array.ndim)
    print('shape:',array.shape)
    print('dtype:',array.dtype)
    print('size:',array.size)
    print('itemsize:',array.itemsize)
    print('nbytes:',array.nbytes)
    print('strides:',array.strides)

In [23]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [24]:
print(a1)
print(a1[0])
print(a1[-1])

[4 5 6 4 5]
4
5


In [25]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3 = np.array( [[ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ]] )

print(a2)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [26]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


In [27]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [28]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


In [29]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [30]:
print('a2:',a2)
print('a2[1]:',a2[1])
print('a2[1, :]',a2[1, :])
print('a2[:2,:2]',a2[:2,:2])
print('a2[1:,::-1]',a2[1:,::-1])
print('a2[::-1,::-1]',a2[::-1,::-1])

a2: [[1 2 3]
 [4 5 6]
 [7 8 9]]
a2[1]: [4 5 6]
a2[1, :] [4 5 6]
a2[:2,:2] [[1 2]
 [4 5]]
a2[1:,::-1] [[6 5 4]
 [9 8 7]]
a2[::-1,::-1] [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [31]:
print(a1)
bi = [False,True,False,True,True]
print(a1[bi])

[4 5 6 4 5]
[5 4 5]


In [32]:
print(a2)
bi = np.random.randint(0,2,(3,3),dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [False  True  True]
 [ True  True  True]]
[2 5 6 7 8 9]


In [33]:
print(a1)
print([a1[0],a1[2]])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1],
              [2,0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [34]:
print(a2)
row = np.array([0,2])

col = np.array([1,2])

print(a2[row,col])

print(a2[row, :])
print(a2[:, col])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [35]:
print(a2[row, 1])
print(a2[2, col])
print(a2[row,1:])
print(a2[1:,col])

[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


In [36]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)
print(a1)
c1 = np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [37]:
print(a2)
b2 = np.insert(a2,1,10,axis = 0)
print(b2)
c2 = np.insert(a2,1,10,axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [38]:
print(a1)
a1[0] = 1 
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1]=9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [39]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)
a2[1:,2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,0])
a2[row,col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [0 2 9]
 [7 8 9]]


In [40]:
print(a1)
b1 = np.delete(a1,1)
print(b1)

[9 4 3 4 4]
[9 3 4 4]


In [41]:
print(a2)
b2 =np.delete(a2,1,axis = 0)
print(b2)
c2 = np.delete(a2,1,axis = 1)
print(c2)

[[1 0 1]
 [0 2 9]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [0 9]
 [7 9]]


In [42]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [0 2 9]
 [7 8 9]]
[[1 0]
 [0 2]]
[[1 0]
 [0 2]]
[[1 0]
 [0 0]]
[[1 0 1]
 [0 0 9]
 [7 8 9]]


In [43]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [0 0 9]
 [7 8 9]]
[[1 0]
 [0 0]]
[[1 1]
 [0 1]]
[[1 0 1]
 [0 0 9]
 [7 8 9]]


In [44]:
print(a2)
print(a2.T)

[[1 0 1]
 [0 0 9]
 [7 8 9]]
[[1 0 7]
 [0 0 8]
 [1 9 9]]


In [45]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [46]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [0 0 9]
 [7 8 9]]
[[1 0 7]
 [0 0 8]
 [1 9 9]]


In [47]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [48]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1 2 3 4 5 6 7 8 9]]


In [50]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[8 9 4 4 9]
 [8 0 6 0 7]]
[[8 9]
 [4 4]
 [9 8]
 [0 6]
 [0 7]]


In [51]:
n2.resize((5,5))
print(n2)

[[8 9 4 4 9]
 [8 0 6 0 7]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [52]:
n2.resize((3,3))
print(n2)

[[8 9 4]
 [4 9 8]
 [0 6 0]]


In [53]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [54]:
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [55]:
c2 = np.append(a2,b2,axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [56]:
c2 = np.append(a2,b2,axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [57]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [58]:
c1=np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [59]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,a2],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [61]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [63]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [64]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [65]:
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1,[5])
print(b1,c1)
b1,c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [66]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 , c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [67]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 , c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [68]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3 , c3 = np.dsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


In [69]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1 + a2)
b2 =np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [70]:
a1 = np.arange(1,10)
print(a1)
print(a1 + 1)
print(np.add(a1,10))
print(a1 - 20)
print(np.subtract(a1,10))
print(-a1)
print(np.negative(a1))
print((a1*2))
print(np.multiply(a1,2))
print((a1/2))
print(np.divide(a1,2))
print(a1//2)
print(np.floor_divide(a1,2))
print(a1**2)
print(np.power(a1,2))
print(a1%2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-19 -18 -17 -16 -15 -14 -13 -12 -11]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [71]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size = 9)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[ 5 11  7 10 12 11 12 16 14]
[-3 -7 -1 -2 -2  1  2  0  4]
[ 4 18 12 24 35 30 35 64 45]
[0.25       0.22222222 0.75       0.66666667 0.71428571 1.2
 1.4        1.         1.8       ]
[0 0 0 0 0 1 1 1 1]
[       1      512       81     4096    78125     7776    16807 16777216
    59049]
[1 2 3 4 5 1 2 0 4]


In [72]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 1 5]
 [3 2 9]
 [5 7 8]]
[[ 4  3  8]
 [ 7  7 15]
 [12 15 17]]
[[-2  1 -2]
 [ 1  3 -3]
 [ 2  1  1]]
[[ 3  2 15]
 [12 10 54]
 [35 56 72]]
[[0.33333333 2.         0.6       ]
 [1.33333333 2.5        0.66666667]
 [1.4        1.14285714 1.125     ]]
[[0 2 0]
 [1 2 0]
 [1 1 1]]
[[       1        2      243]
 [      64       25 10077696]
 [   16807  2097152 43046721]]
[[1 0 3]
 [1 1 6]
 [2 1 1]]


In [73]:
a1 = np.random.randint(-10,10,size = 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 8 -1  3  9  8]
[8 1 3 9 8]
[8 1 3 9 8]


In [74]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 8 -1  3  9  8]
[64  1  9 81 64]
[2.82842712        nan 1.73205081 3.         2.82842712]


C:\Users\hongwon\AppData\Local\Temp/ipykernel_26252/2033102379.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


In [75]:
a1 = np.random.randint(1,10,size = 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[8 3 6 2 6]
[2980.95798704   20.08553692  403.42879349    7.3890561   403.42879349]
[256.   8.  64.   4.  64.]
[64  9 36  4 36]


In [76]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))


[8 3 6 2 6]
[2.07944154 1.09861229 1.79175947 0.69314718 1.79175947]
[3.        1.5849625 2.5849625 1.        2.5849625]
[0.90308999 0.47712125 0.77815125 0.30103    0.77815125]


In [77]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [78]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))


[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [79]:
a2 = np.random.randint(1,10,(3,3))
print(a2)
print(np.sum(a2))
print(np.sum(a2,axis = 0))
print(np.sum(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
51
[13 19 19]
[20 14 17]


In [80]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2,axis = 0))
print(np.cumsum(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
[ 2 11 20 25 33 34 40 42 51]
[[ 2  9  9]
 [ 7 17 10]
 [13 19 19]]
[[ 2 11 20]
 [ 5 13 14]
 [ 6  8 17]]


In [81]:
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis = 0))
print(np.diff(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
[[ 7  0]
 [ 3 -7]
 [-4  7]]
[[ 3 -1 -8]
 [ 1 -6  8]]
[[ 7  0]
 [ 3 -7]
 [-4  7]]


In [82]:
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis = 0))
print(np.prod(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
699840
[ 60 144  81]
[162  40 108]


In [83]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis = 0))
print(np.cumprod(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
[     2     18    162    810   6480   6480  38880  77760 699840]
[[  2   9   9]
 [ 10  72   9]
 [ 60 144  81]]
[[  2  18 162]
 [  5  40  40]
 [  6  12 108]]


In [84]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[20 20 20]
 [14 14 14]
 [17 17 17]]
[[20 20 20]
 [14 14 14]
 [17 17 17]]


In [85]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes = 0))
print(np.tensordot(a2,b2,axes = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
51
[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[20 20 20]
 [14 14 14]
 [17 17 17]]


In [86]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


In [87]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[20 20 20]
 [14 14 14]
 [17 17 17]]
[[2 2 2 2 2 2 2 2 2]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [5 5 5 5 5 5 5 5 5]
 [8 8 8 8 8 8 8 8 8]
 [1 1 1 1 1 1 1 1 1]
 [6 6 6 6 6 6 6 6 6]
 [2 2 2 2 2 2 2 2 2]
 [9 9 9 9 9 9 9 9 9]]


In [88]:
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis = 0))
print(np.mean(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
5.666666666666667
[4.33333333 6.33333333 6.33333333]
[6.66666667 4.66666667 5.66666667]


In [89]:
print(a2)
print(np.std(a2))
print(np.std(a2,axis = 0))
print(np.std(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
3.1269438398822866
[1.69967317 3.09120617 3.77123617]
[3.29983165 2.86744176 2.86744176]


In [90]:
print(a2)
print(np.var(a2))
print(np.var(a2,axis = 0))
print(np.var(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
9.777777777777779
[ 2.88888889  9.55555556 14.22222222]
[10.88888889  8.22222222  8.22222222]


In [91]:
print(a2)
print(np.min(a2))
print(np.min(a2,axis = 0))
print(np.min(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
1
[2 2 1]
[2 1 2]


In [92]:
print(a2)
print(np.max(a2))
print(np.max(a2,axis = 0))
print(np.max(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
9
[6 9 9]
[9 8 9]


In [93]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2,axis = 0))
print(np.argmin(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
5
[0 2 1]
[0 2 1]


In [94]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis = 0))
print(np.argmax(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
1
[2 0 0]
[1 1 2]


In [95]:
print(a2)
print(np.median(a2))
print(np.median(a2,axis = 0))
print(np.median(a2,axis = 1))

[[2 9 9]
 [5 8 1]
 [6 2 9]]
6.0
[5. 8. 9.]
[9. 5. 6.]


In [96]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation = 'midpoint'))


[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [97]:
a2 = np.array([[False,False,False],
              [False,True,True],
              [False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis = 0))
print(np.any(a2,axis = 1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


In [98]:
a2 = np.array([[False,False,True],
              [True,True,True],
              [False,True,True]])

print(a2)
print(np.all(a2))
print(np.all(a2,axis = 0))
print(np.all(a2,axis = 1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


In [99]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [100]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5,axis = 0))
print(np.sum(a2 > 5,axis = 1))
print(np.any(a2 > 5))
print(np.any(a2 > 5,axis = 0))
print(np.any(a2 > 5,axis = 1))
print(np.all(a2 > 5))
print(np.all(a2 > 5,axis = 0))
print(np.all(a2 > 5,axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [101]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(np.isclose(a1,b1))

[1 2 3 4 5]
[ True  True  True False False]


In [102]:
a1 = np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [103]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


In [104]:
a1 = np.random.randint(1,10,size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[5 7 2 2 5 9 9 6 8 5]
[2 2 5 5 5 6 7 8 9 9]
[5 7 2 2 5 9 9 6 8 5]
[2 3 0 4 9 7 1 8 5 6]
[5 7 2 2 5 9 9 6 8 5]
None
[2 2 5 5 5 6 7 8 9 9]


In [105]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2,axis = 0))
print(np.sort(a2,axis = 1))

[[3 7 4]
 [9 1 6]
 [8 5 6]]
[[3 1 4]
 [8 5 6]
 [9 7 6]]
[[3 4 7]
 [1 6 9]
 [5 6 8]]


In [106]:
a1 = np.random.randint(1,10,size = 10)
print(a1)
print(np.partition(a1,3))

[4 8 1 7 8 2 2 4 7 1]
[1 1 2 2 4 4 8 7 7 8]


In [107]:
a2 = np.random.randint(1,10,size = (5,5))
print(a2)
print(np.partition(a2,3,axis = 0))
print(np.partition(a2,3,axis = 1))

[[5 4 1 5 7]
 [4 5 4 9 8]
 [7 6 1 9 5]
 [4 4 2 3 3]
 [3 6 3 6 8]]
[[4 4 1 3 3]
 [3 4 1 5 5]
 [4 5 2 6 7]
 [5 6 3 9 8]
 [7 6 4 9 8]]
[[4 1 5 5 7]
 [4 4 5 8 9]
 [1 5 6 7 9]
 [3 2 3 4 4]
 [3 3 6 6 8]]


In [108]:
a2 = np.random.randint(1,10,size = (5,5))
print(a2)
np.save('a',a2)

[[8 2 2 6 7]
 [7 8 6 6 9]
 [2 1 1 5 6]
 [2 3 6 3 3]
 [7 2 2 4 6]]


In [109]:
!ls

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [110]:
b2 = np.random.randint(1,10,size = (5,5))
print(b2)
np.savez('ab',a2,b2)

[[5 1 2 4 6]
 [9 5 1 2 7]
 [5 6 1 6 8]
 [4 8 6 4 7]
 [1 3 7 4 8]]


In [111]:
!ls

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [112]:
npy = np.load('a.npy')
print(npy)

[[8 2 2 6 7]
 [7 8 6 6 9]
 [2 1 1 5 6]
 [2 3 6 3 3]
 [7 2 2 4 6]]


In [113]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[8 2 2 6 7]
 [7 8 6 6 9]
 [2 1 1 5 6]
 [2 3 6 3 3]
 [7 2 2 4 6]]
[[5 1 2 4 6]
 [9 5 1 2 7]
 [5 6 1 6 8]
 [4 8 6 4 7]
 [1 3 7 4 8]]


In [114]:
print(a2)
np.savetxt('a.csv',a2,delimiter=',')


[[8 2 2 6 7]
 [7 8 6 6 9]
 [2 1 1 5 6]
 [2 3 6 3 3]
 [7 2 2 4 6]]


In [115]:
!ls

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [116]:
!cat.a.csv

'cat.a.csv'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [117]:
csv = np.loadtxt('a.csv',delimiter=',')
print(csv)

[[8. 2. 2. 6. 7.]
 [7. 8. 6. 6. 9.]
 [2. 1. 1. 5. 6.]
 [2. 3. 6. 3. 3.]
 [7. 2. 2. 4. 6.]]


In [118]:
print(b2)
np.savetxt('b.csv',b2,delimiter = ',',fmt = '%.2e',header='c1,c2,c3,c4,c5')

[[5 1 2 4 6]
 [9 5 1 2 7]
 [5 6 1 6 8]
 [4 8 6 4 7]
 [1 3 7 4 8]]


In [119]:
!cat.b.csv

'cat.b.csv'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [120]:
csv = np.loadtxt('b.csv',delimiter = ',')
print(csv)

[[5. 1. 2. 4. 6.]
 [9. 5. 1. 2. 7.]
 [5. 6. 1. 6. 8.]
 [4. 8. 6. 4. 7.]
 [1. 3. 7. 4. 8.]]
